### ISSUE TITLE
Corp script failing on BN 9

### ISSUE THREAD

**Issue by kdog0598** [Sordani/Bitburner-script-building#6]
There is an issue with the corp script where it crashes when trying to expand into pharmaceuticals due to the reduced division cap of BN 9. Issue can be circumvented by selling off some of the original fraud divisions, just wanted to let you know about it if you hadn't already seen that behavior.

```
RUNTIME ERROR
corp.js@home (PID - 309)

Cannot expand into Pharmaceutical industry, too many divisions!
stack:
Error: Cannot expand into Pharmaceutical industry, too many divisions!
    at NewDivision (https://danielyxie.github.io/bitburner/dist/main.bundle.js:2:332773)
    at https://danielyxie.github.io/bitburner/dist/main.bundle.js:2:958147
    at Proxy.l (https://danielyxie.github.io/bitburner/dist/main.bundle.js:2:867524)
    at Business.expansionPlan (home/corp.js:1042:25)
    at Module.main (home/corp.js:1225:7)
    at async N (https://danielyxie.github.io/bitburner/dist/main.bundle.js:2:1033032)
```

**Comment by Sordani** [comment]
this has been noted. bitnode 3 can have 20, so i use 20 to get the numbers. currently there is no logic available that allows automatically selling off divisions, so that's the exact manual action required to get around this.try to keep deltacocorp since it wants to expand to one of every division and will only work deltacocorp. after i accomplish a few other goals in bitburner i might come around and fine tune a more graceful way of frauding investment round 2 with useful divisions instead of restaraunt divisions (they were selected purely because they obtain the highest multiplier for adVerts)
